export const GET_AUTHENTICATED_USER = "GET_AUTHENTICATED_USER";
export const IS_LOADING = "IS_LOADING";
export const USER_LOGOUT = "USER_LOGOUT";
export const CHECK_TOKEN_AVAIL = "CHECK_TOKEN_AVAIL";
